apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ailyze-celeryworkers-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
  storageClassName: managed-premium
