apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ailyze-celery-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-premium
