apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ailyze-companion-pvc
  namespace: uppy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-premium
