apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-redis-deployment
  labels:
    app: ailyze-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-redis
  template:
    metadata:
      labels:
        app: ailyze-redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "400m"
            memory: "400Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-redis-service
spec:
  selector: 
    app: ailyze-redis
  ports:
  - port: 6379
    targetPort: 6379