apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-flower-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-flower
  template:
    metadata:
      labels:
        app: ailyze-flower
    spec:
      containers:
      - name: flower
        image: mher/flower:latest
        command: ["python"]
        args: ["-m", "flower.app.cli"]
        ports:
        - containerPort: 5555
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-broker-url
        - name: FLOWER_BASIC_AUTH
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: flower-basic-auth
        - name: FLOWER_PORT
          value: "5555"   

---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-flower-service
spec:
  selector:
    app: ailyze-flower
  ports:
    - port: 80
      name: http
      targetPort: 5555
  type: LoadBalancer