apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-celery-compare-deployment
  labels:
    app: ailyze-celery-compare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-celery-compare
  template:
    metadata:
      labels:
        app: ailyze-celery-compare
    spec:
      containers:
      - name: celery-compare
        image: celery:latest 
        imagePullPolicy: Always
        command: ["celery", "-A", "AILYZE", "worker", "-l", "info", "-Q", "compareviewpoint", "-n", "compare", "-Ofair"]
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-result-backend
        - name: DJANGO_SETTINGS_MODULE
          value: "AILYZE.settings"  
        volumeMounts:
        - name: app-source
          mountPath: /usr/src/app 
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "3Gi"
      volumes:
      - name: app-source
        persistentVolumeClaim:
          claimName: ailyze-celery-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-celery-compare-service
spec:
  selector:
    app: ailyze-celery-compare
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ailyze-celery-compare-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ailyze-celery-compare-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60