apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-celery-theme-deployment
  labels:
    app: ailyze-celery-theme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-celery-theme
  template:
    metadata:
      labels:
        app: ailyze-celery-theme
    spec:
      containers:
      - name: celery-theme
        image: ailyzeregistery.azurecr.io/ailyze-django:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "sleep 60 && celery -A AILYZE worker -l info -Q themeandresearchquestion -n theme -Ofair"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: user 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: password 
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: db_name 
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-broker-url 
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-result-backend 
        resources:
          requests:
            cpu: "400m"
            memory: "200Mi"
          limits:
            cpu: "800m"
            memory: "400Mi"   
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-celery-theme-service
spec:
  selector:
    app: ailyze-celery-theme
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ailyze-celery-theme-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ailyze-celery-theme-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
