apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-celery-frequency-deployment
  labels:
    app: ailyze-celery-frequency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-celery-frequency
  template:
    metadata:
      labels:
        app: ailyze-celery-frequency
    spec:
      containers:
      - name: celery-frequency
        image: ailyzeregistery.azurecr.io/ailyze-django:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "sleep 60 && celery -A AILYZE worker -l info -Q frequency_analysis -n frequency -Ofair"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: db_name
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-result-backend
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "2024Mi"
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-celery-frequency-service
spec:
  selector:
    app: ailyze-celery-frequency
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ailyze-celery-frequency-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ailyze-celery-frequency-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60