apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-flower-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-flower
  template:
    metadata:
      labels:
        app: ailyze-flower
    spec:
      containers:
      - name: flower
        image:image: mher/flower:0.9.7
        command: ["flower"]
        args: ["--broker=${CELERY_BROKER_URL}", "--port=5555"]
        ports:
        - containerPort: 5555
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-broker-url
        - name: FLOWER_BASIC_AUTH
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: flower-basic-auth
        # Optional: Set resource requests and limits
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-flower-service
spec:
  selector:
    app: ailyze-flower
  ports:
    - port: 80
      targetPort: 5555
      name: http
  type: LoadBalancer
