apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-django-bot-deployment
  labels:
    app: ailyze-django-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-django-bot
  template:
    metadata:
      labels:
        app: ailyze-django-bot
    spec:
      containers:
      - name: ailyze-bot
        image: ailyzeregistery.azurecr.io/ailyze-django:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ailyze-db-secret
              key: password 
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-result-backend
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: redis-url
        command: ["sh", "-c"]
        args:
          - |
            python manage.py migrate &&
            gunicorn --bind 0.0.0.0:8001 AILYZE.wsgi:application -w 2 --log-level info --access-logfile ./bot.access.log --error-logfile ./bot.error.log  
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "3Gi"
      imagePullSecrets:
      - name: acr-secret
---   
apiVersion: v1
kind: Service
metadata:
  name: ailyze-django-bot-service
spec:
  selector: 
    app: ailyze-django-bot
  ports:
    - name: bot
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ailyze-django-bot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ailyze-django-bot-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
    