apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-celery-frequency-deployment
  labels:
    app: ailyze-celery-frequency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-celery-frequency
  template:
    metadata:
      labels:
        app: ailyze-celery-frequency
    spec:
      containers:
      - name: celery-frequency
        image: celery:latest 
        imagePullPolicy: Always
        command: ["celery", "-A", "AILYZE", "worker", "-l", "info", "-Q", "compareviewpoint", "-n", "compare", "-Ofair"]
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-result-backend
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "3Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-celery-frequency-service
spec:
  selector:
    app: ailyze-celery-frequency
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ailyze-celery-frequency-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ailyze-celery-frequency-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60