apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-celery-bot-deployment
  labels:
    app: ailyze-celery-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-celery-bot
  template:
    metadata:
      labels:
        app: ailyze-celery-bot
    spec:
      containers:
      - name: celery-bot
        image: ailyzeregistery.azurecr.io/ailyze-django:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "AILYZE", "worker", "-l", "info", "-Q", "prepare_bot", "-n", "$(POD_NAME)-bot", "-Ofair","-E"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: celery-result-backend
        - name: DJANGO_SETTINGS_MODULE
          value: "AILYZE.settings"  
        volumeMounts:
        - name: app-source
          mountPath: /usr/src/app 
        resources:
          requests:
            memory: "1500Mi"
          limits:
            memory: "4Gi"
      volumes:
      - name: app-source
        persistentVolumeClaim:
          claimName: ailyze-celeryworkers-pvc
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-celery-bot-service
spec:
  selector:
    app: ailyze-celery-bot
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ailyze-celery-bot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ailyze-celery-bot-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60