apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ailyze-rabbitmq-statefullset
  labels:
    app: ailyze-rabbitmq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ailyze-rabbitmq
  template:
    metadata:
      labels:
        app: ailyze-rabbitmq
    spec:
      initContainers:
      - name: init-rabbitmq
        image: busybox
        command: ["sh", "-c", "chmod 600 /var/lib/rabbitmq/.erlang.cookie"]
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: rabbitmq_user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: rabbitmq_password
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: erlang_cookie
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: ailyze-rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-rabbitmq-headless
  labels:
    app: ailyze-rabbitmq
spec:
  clusterIP: None
  selector:
    app: ailyze-rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-rabbitmq-service
  labels:
    app: ailyze-rabbitmq
spec:
  selector:
    app: ailyze-rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ailyze-rabbitmq-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: ailyze-rabbitmq-statefullset
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
