apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-react-deployment
  labels:
    app: ailyze-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-react
  template:
    metadata:
      labels:
        app: ailyze-react
    spec:
      containers:
      - name: ailyze-web-app
        imagePullPolicy: Always
        image: ailyzeregistery.azurecr.io/ailyze-react:latest
        ports:
        - containerPort: 3020
        command: ["npm", "start"] 
        # resources:
        #   requests:
        #     cpu: "250m"
        #     memory: "512Mi"
        #   limits:
        #     cpu: "1000m"
        #     memory: "2048Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-react-service
spec:
  selector:
    app: ailyze-react
  ports:
  - port: 80
    name: http
    targetPort: 3020
  - port: 443
    name: https
    targetPort: 3020
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ailyze-react-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ailyze-react-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50