apiVersion: apps/v1
kind: Deployment
metadata:
  name: ailyze-react-deployment
  labels:
    app: ailyze-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ailyze-react
  template:
    metadata:
      labels:
        app: ailyze-react
    spec:
      containers:
      - name: ailyze-web-app
        imagePullPolicy: Always
        image: ailyzeregistery.azurecr.io/ailyze-react:latest
        ports:
        - containerPort: 3020
        command: ["npm", "start"] 
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-react-service
spec:
  selector:
    app: ailyze-react
  ports:
  - port: 80
    name: http
    targetPort: 3020
  - port: 443
    name: https
    targetPort: 3020
  type: LoadBalancer
      