apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-new-companion
  namespace: uppy
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ailyze@outlook.com
    privateKeySecretRef:
      name: letsencrypt-companion
    solvers:
    - http01:
        ingress:
          class: nginx