apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ailyze-newreact-ssl
spec:
  secretName: ailyze-newreact-ssl
  issuerRef:
    name: ailyze-react
    kind: ClusterIssuer
  commonName: ailyze.com
  dnsNames:
    - ailyze.com
    - www.ailyze.com
  usages:
    - digital signature
    - key encipherment
