apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ailyze-django-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.ailyze.com
    secretName: ailyze-django-ssl
  rules:
  - host: demo.ailyze.com
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: ailyze-django-service
            port:
              number: 80
        path: /
      - pathType: Prefix
        backend:
          service:
            name: ailyze-django-service
            port:
              number: 8001
        path: /bot

  