apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ailyze-django-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.ailyze.com
    secretName: ailyze-django-ssl
  rules:
  - host: demo.ailyze.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ailyze-django-service
            port:
              number: 80
      - path: /bot
        pathType: Prefix
        backend:
          service:
            name: ailyze-django-service
            port:
              number: 8001
        

  