apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ailyze-rabbitmq-statefulset
  labels:
    app: ailyze-rabbitmq-cluster
spec:
  serviceName: ailyze-rabbitmq-headless
  replicas: 3
  selector:
    matchLabels:
      app: ailyze-rabbitmq-cluster
  template:
    metadata:
      labels:
        app: ailyze-rabbitmq-cluster
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq
        image: rabbitmq:3.11-management
        imagePullPolicy: IfNotPresent
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        - name: epmd
          containerPort: 4369
        - name: cluster-rpc
          containerPort: 25672
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: ailyze-secret
              key: erlang-cookie
        - name: K8S_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: K8S_SERVICE_NAME
          value: ailyze-rabbitmq-headless
        - name: RABBITMQ_NODENAME
          value: "rabbit@$(K8S_HOSTNAME).$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc.cluster.local"
        - name: K8S_HOSTNAME_SUFFIX
          value: ".$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc.cluster.local"
        command:
        - sh
        - -c
        - |
          echo $RABBITMQ_ERLANG_COOKIE > /var/lib/rabbitmq/.erlang.cookie
          chmod 600 /var/lib/rabbitmq/.erlang.cookie
          exec docker-entrypoint.sh rabbitmq-server
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/enabled_plugins
          subPath: enabled_plugins
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_port_connectivity"]
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "status"]
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 6
          timeoutSeconds: 15
      volumes:
      - name: rabbitmq-config
        configMap:
          name: rabbitmq-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = ailyze-rabbitmq-headless
    cluster_formation.k8s.hostname_suffix = .ailyze-rabbitmq-headless.$(K8S_NAMESPACE).svc.cluster.local
    cluster_formation.node_cleanup.interval = 30
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    queue_master_locator = min-masters
    loopback_users.guest = false
    cluster_formation.randomized_startup_delay_range.min = 0
    cluster_formation.randomized_startup_delay_range.max = 60
    cluster_formation.discovery_retry_limit = 10
    cluster_formation.discovery_retry_interval = 500
    feature_flags.tracking_records_in_ets = false
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_peer_discovery_k8s].
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-rabbitmq-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: amqp
    port: 5672
  - name: management
    port: 15672
  - name: epmd
    port: 4369
  - name: cluster-rpc
    port: 25672
  selector:
    app: ailyze-rabbitmq-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: ailyze-rabbitmq-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  selector:
    app: ailyze-rabbitmq-cluster