apiVersion: v1
kind: Secret
metadata:
  name: ailyze-secret
type: Opaque
stringData:
  celery-broker-url: amqp://productionuser:productionpassword@ailyze-rabbitmq-service:5672//
  celery-result-backend: redis://ailyze-redis-service:6379/0
  flower-basic-auth: admin:Ailyzeadmin
  rabbitmq_user: productionuser
  rabbitmq_password: productionpassword
  erlang_cookie: ailyzeerlandcookievalue
  redis-url: redis://ailyze-redis-service:6379/0